import { type NextRequest, NextResponse } from "next/server"

const laborDeployments = [
  {
    id: "1",
    date: "01/08/2024 08:00",
    task: "Harvesting",
    location: "Field A",
    employees: 5,
    hours: 8,
    notes: "Started harvesting in Field A. Good weather conditions.",
  },
  {
    id: "2",
    date: "01/08/2024 16:00",
    task: "Irrigation",
    location: "Field B",
    employees: 2,
    hours: 4,
    notes: "Irrigation in Field B. Minor pump malfunction, delayed by 30 minutes.",
  },
  {
    id: "3",
    date: "02/08/2024 08:00",
    task: "Planting",
    location: "Field C",
    employees: 4,
    hours: 8,
    notes: "Planting seedlings in Field C. Soil quality is excellent.",
  },
  {
    id: "4",
    date: "02/08/2024 10:00",
    task: "Pest Control",
    location: "Field A",
    employees: 3,
    hours: 6,
    notes: "Applying organic pest control in Field A. Aphids detected.",
  },
  {
    id: "5",
    date: "03/08/2024 08:00",
    task: "Weeding",
    location: "Field B",
    employees: 6,
    hours: 8,
    notes: "Manual weeding in Field B. Weed growth is moderate.",
  },
  {
    id: "6",
    date: "03/08/2024 14:00",
    task: "Fertilizing",
    location: "Field C",
    employees: 2,
    hours: 4,
    notes: "Applying fertilizer in Field C. Used a new fertilizer mix.",
  },
  {
    id: "7",
    date: "04/08/2024 08:00",
    task: "Pruning",
    location: "Field A",
    employees: 3,
    hours: 8,
    notes: "Pruning tomato plants in Field A. Removed diseased leaves.",
  },
  {
    id: "8",
    date: "04/08/2024 12:00",
    task: "Soil Testing",
    location: "Field B",
    employees: 1,
    hours: 4,
    notes: "Collecting soil samples in Field B for lab analysis.",
  },
  {
    id: "9",
    date: "05/08/2024 08:00",
    task: "Watering",
    location: "Field C",
    employees: 2,
    hours: 6,
    notes: "Watering newly planted seedlings in Field C.",
  },
  {
    id: "10",
    date: "05/08/2024 11:00",
    task: "Equipment Maintenance",
    location: "Workshop",
    employees: 2,
    hours: 8,
    notes: "Servicing tractors and irrigation pumps in the workshop.",
  },
]

export async function GET(request: NextRequest) {
  return NextResponse.json({ deployments: laborDeployments })
}
